### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by marcelbuesing** [carllerche/codegen#15]
I would be grateful if you could release a new version, including the two latest pull requests (#12, #13). Both changes should be non breaking.

I am planning to release a [crate](https://github.com/marcelbuesing/can-dbc/tree/dev/dbcc) based on the changes.

**Comment by carllerche** [comment]
Done, thanks 👍

**Comment by carllerche** [comment]
PS, I added you as a collaborator, so you have commit rights (as you are going to depend on it :+1:)
