### ISSUE TITLE
Code generation?

### ISSUE THREAD

**Issue by piranna** [carllerche/codegen#22]
So far docs and tests show only high level components can be generated, like structs, modules and functions, and code needs yo be created with raw code strings at Function.line(). Not sure if it's a limitation of the builder pattern used un the API, but how much would cost to add support for generation of variables, asignements, blocks, loops, conditionals and function calls?

**Comment by andrewleverette** [comment]
I could see adding constructs for loops and maybe function calls. I think that variable assignments and conditionals are at to low of a level to warrant building logic around that. Plus it would take away quite a bit of flexibility.

**Comment by piranna** [comment]
Flexibility would be drop if `raw` calls would be removed, but I think they are still useful. I've been investigating os using `libsyntax` and other tools, but seems they doesn't fit or are simple enought for code generation. I understand your concerns about making code more complex, but I only see it as a matter of adding some more extra builder functions...
