### ISSUE TITLE
Split in múltiple files

### ISSUE THREAD

**Issue by piranna** [carllerche/codegen#23]
Lib.rs file is almost 2000 lines of code, wouldn't It be better to split un a file for each Item type? Also, some methods are duplicarse, and by being traits its code could be reused between several Items...

**Comment by BaeoMaltinsky** [comment]
I agree that it would be a bit nicer that way. Splitting it into separate files and re-exporting in `lib.rs` should be a quick job.

**Comment by piranna** [comment]
Done at #24. Not so much a quick job, but it allowed me to practice a bit :-)
