### ISSUE TITLE
Field documentation

### ISSUE THREAD

**Issue by nbigaouette-eai** [carllerche/codegen#4]
It'd be interesting to be able to add (structs' and fields') fields documentation.

For example:
```rust
let mut scope = Scope::new();

scope.new_struct("Foo").field("bar", "i64", "This is a `bar`");
```
could generate:
```rust
struct Foo {
    /// This is a `bar`
    bar: i64,
}
```

Or maybe a `Field` type would be useful which could be `push_field()`ed to a `Struct`, similarly to `Scope::push_struct()`?

**Comment by carllerche** [comment]
:+1: I would probably not include the doc string as a third argument as that could get unwieldy.

A `push_field` would most definitely be useful either way, so we can add doc (and annotation) support to that.
